// pages/characters/index.jsx

import { useState, useEffect} from 'react'
import Link from 'next/link'
import Layout from '~/components/Layout'
import Button from '~/components/buttons/Button'
import { allCharacters } from '~/lib/character'

const Characters = () => {
	const [characters, setCharacters] = useState([])

	useEffect(async () => {
		const result = await allCharacters()

		setCharacters(result)
	}, [])

	return <Layout title="Characters">
		<p>Some blurb about creating a character.</p>
		<section>
			<ol>
				{ characters.map(character => <li key={ character.id }>
					<Link href={ `/characters/${character.id}` }>
						<a className="text-blue-600 underline">{ character.name || `Unnamed character (${character.id})` }</a>
					</Link>
				</li>) }
			</ol>
		</section>
		<Button href='/characters/new'>New Character</Button>
	</Layout>
}

export default Characters

// pages/characters/index.vue
<template>
	<main class="pt-12 relative">
		<p>Some blurb about creating a character.</p>
		<Loading v-if="$fetchState.pending" />
		<section v-else>
			<ol class="m-3 list">
				<li :key="`character_${character.id}`" v-for="(character, idx) in characters">
					<nuxt-link :to="`/characters/${character.id}`">
						<a className="text-blue-600 underline">{{ character.name || `Unnamed character (${character.id})` }}</a>
					</nuxt-link>
				</li>
			</ol>
		</section>
		<Link class="btn" to="/characters/new">New Character</Link>
	</main>
</template>
<script>
import Vue from 'vue'

export default {
	async fetch() {
		this.characters = await this.$store.dispatch('character/fetch')
	},

	data() {
		return {
			characters: []
		}
	},
}
</script>
