// components/Button.vue
<template>
	<button :class="classList" :disabled="disabled" @click="$emit('click')">
		<slot />
	</button>
</template>
<script>
import Vue from 'vue'

export default Vue.component('Button', {
	props: {
		disabled: {
			type: Boolean,
			default: false,
		},
		type: {
			type: String,
			default: 'primary',
		},
		block: {
			type: Boolean,
			default: false,
		},
	},

	computed: {
		classList() {
			let classList = ['btn']

			if(this.block === true) {
				classList.push('block w-full')
			}

			if(this.disabled === true) {
				classList.push('disabled')
			}
			else {
				classList.push('enabled')
				classList.push(this.type)
			}

			return classList.join(' ')
		},
	}
})
</script>

// components/buttons/Button.jsx

import { useRouter } from 'next/router'

const Button = ({ href, onClick, disabled, type, block, children }) => {
	const router = useRouter()

	const handler = () => {
		if(disabled === true) {
			return
		}

		if(onClick) {
			onClick()
		}

		if(href) {
			router.push(href)
		}
	}

	let classList = ['btn']

	if(block === true) {
		classList.push('block w-full')
	}

	if(disabled === true) {
		classList.push('disabled')
	}
	else {
		classList.push('enabled')

		if(type) {
			classList.push(type)
		}
		else {
			classList.push('primary')
		}
	}

	return <button onClick={ handler } className={ classList.join(' ') }>{ children }</button>
}

export default Button
