// components/buttons/Stepper.jsx

import { useState, useEffect } from 'react'
import { useRouter } from 'next/router'
import { saveCharacter } from '~/lib/character'
import Button from './Button'
import LoadingButton from './LoadingButton'

const Stepper = ({ character, previous, next, disabled }) => {
	const [loading, setLoading] = useState(false)
	const router = useRouter()

	const clickHandler = async () => {
		setLoading(true)
		await saveCharacter(character)

		router.push(next)
		setLoading(false)
	}

	return <div>
		{ previous ? <Button href={ previous } type="secondary">Previous</Button> : null }
		<LoadingButton loading={ loading } onClick={ clickHandler } disabled={ disabled }>Next</LoadingButton>
	</div>
}

export default Stepper

// components/buttons/Stepper.vue
<template>
	<div class="flex">
		<Link block type="secondary" :to="previous" v-if="previous">Previous</Link>
		<Link block type="secondary" to="/" v-else>Exit</Link>
		<Button block :disabled="disabled" @click="nextClick">Next</Button>
	</div>
</template>
<script>
import Vue from 'vue'

export default Vue.component('Stepper', {
	props: {
		next: {
			type: String,
			required: true,
		},
		previous: {
			type: String,
			default: '',
		},
		disabled: {
			type: Boolean,
			default: false,
		},
	},

	methods: {
		nextClick() {
			this.$emit('click')
			this.$router.push(this.next)
		}
	},
})
</script>
