// components/buttons/ButtonGroup.jsx

import LinkButton from '~/components/buttons/LinkButton'

const ButtonGroup = ({ options, onChange }) => <div className="btn-group">
		{ options.map(opt => <LinkButton key={ opt.value } onClick={ () => onChange(opt.value) } { ...opt }>{ opt.text || opt.value }</LinkButton> )}
	</div>

export default ButtonGroup

// src/components/buttons/ButtonGroup.vue
<template>
	<div class="btn-group">
		<button-action :key="`${opt.value}_${idx}`" v-for="(opt, idx) in options"
			:disabled="opt.disabled"
			:type="opt.type || (opt.value === value ? 'success' : 'primary')"
			@click="$emit('input', opt.value)"
		>
			{{ opt.text || opt.value }}
		</button-action>
	</div>
</template>
<script>
import Vue from 'vue'

export default Vue.component('ButtonGroup', {
	props: {
		value: {
			type: [String, Number],
			required: true,
		},
		options: {
			type: Array,
			required: true,
		},
	},
})
</script>
