// components/cards/CardGrid.jsx

import LinkButton from '../buttons/LinkButton'
import Card from './Card'

const CardGrid = ({ cards, selected, toggleSelected }) =>	<div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-5">
		{ cards.map(card => <div key={ card.id }>
				<Card { ...card } />
				<LinkButton
					block
					onClick={ () => toggleSelected(card) }
					type={ selected && selected.id === card.id ? 'success' : 'secondary' }
				>Use Card</LinkButton>
			</div>
		) }
	</div>

export default CardGrid

// components/cards/CardGrid.vue
<template>
	<div class="grid grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5">
		<div :key="`card_${card.id}`" v-for="card in cards">
			<Card :card="card" />
			<Button
				block
				@click="$emit('click', card)"
				:type="selected && selected === card.id ? 'success' : 'secondary'"
			>
				Use Card
			</Button>
		</div>
	</div>
</template>
<script>
import Vue from 'vue'

export default Vue.component('CardGrid', {
	props: {
		cards: {
			type: Array,
			required: true,
		},
		selected: {
			type: String,
			default: null,
		}
	},
})

</script>
