// components/TextArea.vue
<template>
	<FormField :label="label" :message="message" :error="error" v-slot="field">
		<textarea
			:id="field.id"
			:value="value"
			type="text"
			:class="inputClass"
			:disabled="disabled"
			:placeholder="placeholder"
			@input="$emit('input', $event.target.value)"
		/>
	</FormField>
</template>
<script>
import Vue from 'vue'

export default Vue.component('TextArea', {
	props: {
		value: {
			type: String,
			required: true,
		},
		label: {
			type: String,
			required: true,
		},
		message: {
			type: String,
			default: '',
		},
		error: {
			type: Boolean,
			default: false,
		},
		disabled: {
			type: Boolean,
			default: false,
		},
		placeholder: {
			type: String,
			default: '',
		},
	},

	computed: {
		inputClass() {
			let classList = ['input']

			if(this.disabled) {
				classList.push('disabled')
			}

			if(this.error) {
				classList.push('warning')
			}

			return classList.join(' ')
		},
	},
})

</script>

// components/inputs/TextArea.jsx

import { id } from '~/utils/string'
import FormField from './FormField'

const TextArea = ({ label, value, message, error, disabled, onChange }) => {
	const htmlFor = 'input-' + id(label)
	const handler = (evt) => {
		if(onChange) {
			onChange(evt.target.value)
		}
	}

	const classList = ['input']

	if(disabled) {
		classList.push('disabled')
	}

	if(error) {
		classList.push('warning')
	}

	return <FormField label={ label } message={ message } error={ error }>
		<textarea
			id={ htmlFor }
			value={ value }
			onChange={ handler }
			type="text"
			className={ classList.join(' ') }
			disabled={ disabled }
		/>
	</FormField>
}

export default TextArea
